[package]
name = "cyberforenx-academy-backend"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bcrypt = "0.10.1"
mongodb = "2.0.0"
futures = "0.3"